# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: apisix-conf
# data:
#   "config.yaml": |-
#     apisix:
#       enable_admin: false
#       config_center: yaml
#     plugin_attr:
#       prometheus:
#         export_uri: /prometheus/metrics
#         enable_export_server: false
#   "apisix.yaml": |-
#     routes:
#       - uri: /hello/*
#         host: "*"
#         upstream:
#           type: roundrobin
#           nodes:
#             "go-app:8080": 1
#         plugins:
#           proxy-rewrite:
#             regex_uri:
#               - "/hello/(.*)"
#               - "/$1"
#     global_rules:
#       - id: 1
#         plugins:
#           prometheus:
#             prefer_name: true

# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: apisix
# spec:
#   selector:
#     matchLabels:
#       app: apisix
#   template:
#     metadata:
#       labels:
#         app: apisix
#     spec:
#       containers:
#         - name: apisix
#           image: apache/apisix:2.15.0-alpine
#           resources: {}
#           ports:
#             - containerPort: 9080
#           readinessProbe:
#             failureThreshold: 6
#             initialDelaySeconds: 10
#             periodSeconds: 10
#             successThreshold: 1
#             tcpSocket:
#               port: 9080
#             timeoutSeconds: 1
#           lifecycle:
#             preStop:
#               exec:
#                 command:
#                   - /bin/sh
#                   - -c
#                   - "sleep 30"
#           volumeMounts:
#             - name: apisix-config
#               mountPath: /usr/local/apisix/conf/config.yaml
#               subPath: config.yaml
#             - name: apisix-config
#               mountPath: /usr/local/apisix/conf/apisix.yaml
#               subPath: apisix.yaml
#       volumes:
#         - configMap:
#             name: apisix-conf
#           name: apisix-config

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: apisix
# spec:
#   selector:
#     app: apisix
#   ports:
#     - port: 9080
#       targetPort: 9080
